version: '2'

services:

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./laradock/php-fpm
            dockerfile: Dockerfile-70
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace

### Laravel Application Code Container ######################

    application:
        build: ./laradock/application
        volumes:
            - ./:/var/www/laravel

### Databases Data Container ################################

    data:
        build: ./laradock/data
        volumes:
            - ./laradock/container_data/mysql:/var/lib/mysql
            - ./laradock/container_data/postgres:/var/lib/postgres
            - ./laradock/container_data/mariadb:/var/lib/mariadb
            - ./laradock/container_data/memcached:/var/lib/memcached
            - ./laradock/container_data/redis:/data
            - ./laradock/container_data/neo4j:/var/lib/neo4j/data
            - ./laradock/container_data/mongo:/data/db

### Nginx Server Container ##################################

    nginx:
        build: ./laradock/nginx
        volumes_from:
            - application
        volumes:
            - ./laradock/logs/nginx/:/var/log/nginx
        ports:
            - "80"
            - "443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build: ./laradock/mysql
        volumes_from:
            - data
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### PostgreSQL Container ####################################

    postgres:
        build: ./laradock/postgres
        volumes_from:
            - data
        ports:
            - "5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### MariaDB Container #######################################

    mariadb:
        build: ./laradock/mariadb
        volumes_from:
            - data
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Neo4j Container #########################################

    neo4j:
        build: ./laradock/neo4j
        ports:
            - "7474"
            - "1337"
        environment:
            - NEO4J_AUTH=homestead:secret
        volumes_from:
            - data

### MongoDB Container #######################################

    mongo:
        build: ./laradock/mongo
        ports:
            - "27017"
        volumes_from:
            - data

### Redis Container #########################################

    redis:
        build: ./laradock/redis
        volumes_from:
            - data
        ports:
            - "6379"

### Memcached Container #####################################

    memcached:
        build: ./laradock/memcached
        volumes_from:
            - data
        ports:
            - "11211"
        links:
            - php-fpm

### Beanstalkd Container ####################################

    beanstalkd:
        build: ./laradock/beanstalkd
        ports:
            - "11300"
        privileged: true
        links:
            - php-fpm

### Beanstalkd Console Container ############################

    beanstalkd-console:
        build: ./laradock/beanstalkd-console
        ports:
            - "2080"
        links:
            - beanstalkd

### Workspace Utilities Container ###########################

    workspace:
        build: ./laradock/workspace
        volumes_from:
            - application
        tty: true

### Add more Containers below ###############################
